version: '3.4'
services:
  postgres:
    environment:
      POSTGRES_USER: secret_db_username # TODO: read this from credentials
      POSTGRES_PASSWORD: secret_db_password
    volumes:
      - postgres_prod:/var/lib/postgresql/data
      - postgres_prod_tmp:/var/run

  web:
    build:
      target: production
    image: pong_web:prod
    restart: always

volumes:
  postgres_prod:
  postgres_prod_tmp: