version: '3.4'
services:
  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/pong/data/db/production:/var/lib/postgresql/data

  web:
    image: pong_web:prod
    restart: always
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
