version: '3'
services:
  postgres:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_PASSWORD: rails
      POSTGRES_USER: rails
      POSTGRES_MULTIPLE_DATABASES: pong_development, pong_test
      
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - .:/pong
