version: '3.4'
services:
  postgres:
    image: postgres:11.4
    restart: always
    volumes:
      - db_tmp:/var/run

  web:
    image: pong_web
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  db_tmp: &tmp_fs
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs