version: '3'
services:
  postgres:
    # restart: always
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
      
  web:
    image: pong_web:prod
    # restart: always
    # environment:
    #   DB_USER: rails
    #   DB_PASSWORD: rails
