development:
  adapter: postgresql
  encoding: unicode
  database: pong_development
  pool: 5
  username: rails
  password: rails
  host: postgres
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: pong_test
  pool: 5
  username: rails
  password: rails
  host: postgres
  port: 5432
