default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  # username: <%= ENV['DB_USER'] || 'rails' %>
  # password: <%= ENV['DB_PASSWORD'] || 'rails' %>
  username: rails
  password: rails
  port: 5432

development:
  <<: *default
  database: pong_development

test:
  <<: *default
  database: pong_test

production:
  <<: *default
  database: pong_production
