default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: rails
  password: rails
  port: 5432

development:
  <<: *default
  database: pong_development

test:
  <<: *default
  database: pong_test

production:
  <<: *default
  database: pong_production
  username: <%= Rails.application.credentials.dig(:production, :postgres, :username) %>
  password: <%= Rails.application.credentials.dig(:production, :postgres, :password) %>
